version: '3.7'

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS=true
    volumes:
      - cassandra-persistence:/bitnami

volumes:
  cassandra-persistence:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './cassandra-persistence'